### PR TITLE
Sorted notes with respect to upload date, issue #1

### PR DESCRIPTION
**Pull request by Karanagarwal12**
Sorted the Notes with respect to the date added as mentioned in the issue #1.

### CODE REVIEW

**Comment by AkhileshJyotishi** [comment]
@Karanagarwal12 

You need to provide a button on frontend (below the add Note Button ) through which user can sort the sort the notes 
based on his choice.
Also add a screenshot or video showing the changes you have made. 

Thanks!

**Comment by Karanagarwal12** [comment]
Done, Added the buttons to sort the notes with respect to dates.
Thanks for clarifying
Screenshots attached 

notesSort2
notesSort1

**Review by AkhileshJyotishi — COMMENTED** [review]
@Karanagarwal12 

Your PR looks good. 

In NotesAPI.js  , please update the sortNotes function

You can use  this Code Snippet ...
<code>
   static sortNotes(order) {
    const notes = NotesAPI.getAllNotes();
    notes.sort((obj1, obj2) => {
        const date1 = new Date(obj1.updated);
        const date2 = new Date(obj2.updated);
        return order ? (date1 - date2) : (date2 - date1);
    });
    localStorage.setItem("notesapp-notes", JSON.stringify(notes));
}
</code>

Thanks!

**Comment by Karanagarwal12** [comment]
Done, I've changed the function as you said.

**Comment by AkhileshJyotishi** [comment]
Closed :+1:

**Pull request closed without merging**
